Mesd\FilterBundle\Entity\FilterAssociation:
    type: entity
    table: mesd_filter_association
    repositoryClass: Mesd\FilterBundle\Repository\FilterAssociationRepository
    uniqueConstraints:
        mesd_filterbundle__filter_association__name:
            columns:
                - name

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        name:
            type: string
            column: name
            nullable: false
        trail:
            type: text
            column: trail
            nullable: false

    manyToMany:
        filterJoin:
            targetEntity: FilterJoin
            mappedBy: filterAssociation

        filterCategory:
            targetEntity: FilterCategory
            mappedBy: filterAssociation

    manyToOne:
        filterEntity:
            targetEntity: FilterEntity
            inversedBy: filterAssociation

    oneToMany:
        filterCell:
            targetEntity: FilterCell
            mappedBy: filterAssociation
