Mesd\FilterBundle\Entity\FilterEntity:
    type: entity
    table: mesd_filter_entity
    repositoryClass: Mesd\FilterBundle\Repository\FilterEntityRepository
    uniqueConstraints:
        mesd_filterbundle__filter_entity__unique__name:
            columns:
                - name
        mesd_filterbundle__filter_entity__unique__namespace_name:
            columns:
                - namespace_name
        mesd_filterbundle__filter_entity__unique__database_name:
            columns:
                - database_name
    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        name:
            type: string
            column: name
            nullable: false
        ormName:
            type: string
            column: orm_name
            nullable: false
        namespaceName:
            type: string
            column: namespace_name
            nullable: false
        databaseName:
            type: string
            column: database_name
            nullable: false

    manyToMany:
        categoryAssociation:
            targetEntity: FilterAssociation
            inversedBy: categoryEntity
            cascade: {  }
            joinTable:
                name: mesd_filter_entity__association
                joinColumns:
                    filter_entity_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_association_id:
                        referencedColumnName: id

    oneToMany:
        filterAssociation:
            targetEntity: FilterAssociation
            mappedBy: filterEntity
        trailAssociation:
            targetEntity: FilterAssociation
            mappedBy: trailEntity
        filterCategory:
            targetEntity: FilterCategory
            mappedBy: filterEntity
        filter:
            targetEntity: Filter
            mappedBy: filterEntity
