Mesd\FilterBundle\Entity\Filter:
    type: entity
    table: mesd_filter
    repositoryClass: Mesd\FilterBundle\Repository\FilterRepository
    uniqueConstraints:
        mesd_filterbundle__filter__unique__name:
            columns:
                - name
        mesd_filterbundle__filter__unique__description:
            columns:
                - description

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        name:
            type: string
            column: name
            nullable: false
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filterRow:
            targetEntity: FilterRow
            inversedBy: filter
            cascade: {  }
            joinTable:
                name: mesd_filter__row
                joinColumns:
                    filter_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_row_id:
                        referencedColumnName: id

    manyToOne:
        filterCategory:
            targetEntity: FilterCategory
            inversedBy: filter
            joinColumn:
                name: filter_category_id
