Mesd\FilterBundle\Entity\FilterCell:
    type: entity
    table: mesd_filter_cell
    repositoryClass: Mesd\FilterBundle\Repository\FilterCellRepository
    uniqueConstraints:
        mesd_filterbundle__filter_cell__unique__description__filter_association_id:
            columns:
                - description
                - filter_association_id
        mesd_filterbundle__filter_cell__unique__solvent__filter_association_id:
            columns:
                - solvent
                - filter_association_id

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false
        solvent:
            type: json_array
            column: solvent
            nullable: false

    manyToMany:
        filterRow:
            targetEntity: FilterRow
            mappedBy: filterCell

    manyToOne:
        filterAssociation:
            targetEntity: FilterAssociation
            inversedBy: filterCell
            joinColumn:
                name: filter_association_id
