Mesd\FilterBundle\Entity\FilterJoin:
    type: entity
    table: mesd_filter_join
    repositoryClass: Mesd\FilterBundle\Repository\FilterJoinRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        value:
            type: integer
            column: value
            nullable: false
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filterCell:
            targetEntity: FilterCell
            mappedBy: filterJoin
