Mesd\FilterBundle\Entity\FilterRow:
    type: entity
    table: mesd_filter_row
    repositoryClass: Mesd\FilterBundle\Repository\FilterRowRepository
    uniqueConstraints:
        mesd_filterbundle__filter_row__unique__description:
            columns:
                - description

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false
        solvent:
            type: json_array
            column: solvent
            nullable: false

    manyToMany:
        filter:
            targetEntity: Filter
            mappedBy: filterRow

        filterCell:
            targetEntity: FilterCell
            inversedBy: filterRow
            cascade: {  }
            joinTable:
                name: mesd_filter_row__cell
                joinColumns:
                    filter_row_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_cell_id:
                        referencedColumnName: id
