Mesd\FilterBundle\Entity\FilterCategory:
    type: entity
    table: mesd_filter_category
    repositoryClass: Mesd\FilterBundle\Repository\FilterCategoryRepository
    uniqueConstraints:
        mesd_filterbundle__filter_category__name:
            columns:
                - name
        mesd_filterbundle__filter_category__code_name:
            columns:
                - code_name

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        name:
            type: string
            column: name
            nullable: false
        codeName:
            type: string
            column: code_name
            nullable: false

    oneToMany:
        filter:
            targetEntity: Filter
            mappedBy: filterCategory
