Mesd\FilterBundle\Entity\FilterCell:
    type: entity
    table: mesd_filter_cell
    repositoryClass: Mesd\FilterBundle\Repository\FilterCellRepository
    uniqueConstraints:
        mesd_filterbundle__filter_cell__description:
            columns:
                - description

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filterRow:
            targetEntity: FilterRow
            mappedBy: filterCell

    manyToOne:
        filterAssociation:
            targetEntity: FilterAssociation
            inversedBy: filterCell
