Mesd\FilterBundle\Entity\FilterCategory:
    type: entity
    table: mesd_filter_category
    repositoryClass: Mesd\FilterBundle\Repository\FilterCategoryRepository
    uniqueConstraints:
        mesd_filterbundle__filter_category__unique__name:
            columns:
                - name
        mesd_filterbundle__filter_category__unique__code_name:
            columns:
                - code_name

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        name:
            type: string
            column: name
            nullable: false
        codeName:
            type: string
            column: code_name
            nullable: false

    manyToMany:
        filterAssociation:
            targetEntity: FilterAssociation
            inversedBy: filterCategory
            cascade: {  }
            joinTable:
                name: mesd_filter_category__association
                joinColumns:
                    filter_category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_association_id:
                        referencedColumnName: id
    manyToOne:
        filterEntity:
            targetEntity: FilterEntity
            inversedBy: filterCategory
            joinColumn:
                name: filter_entity_id

    oneToMany:
        filter:
            targetEntity: Filter
            mappedBy: filterCategory
