parameters:
    mesd_filter.filter_manager.class: Mesd\FilterBundle\Model\FilterManager

services:
    mesd_filter.filter_manager:
        class: %mesd_filter.filter_manager.class%
        arguments: [@security.context]

    mesd_filter.filter_code_to_row_transformer_factory:
        class: Mesd\FilterBundle\Form\Factory\FilterCodeToRowTransformerFactory
        arguments: ["@doctrine"]


    mesd_filter.type.filter:
        class: Mesd\FilterBundle\Form\Type\FilterType
        arguments: ["@mesd_filter.filter_code_to_row_transformer_factory"]
        tags:
          - { name: form.type, alias: mesd_filterbundle_filter }
