language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

install:
    - composer install --prefer-dist

script:
    # --coverage-clover for Coveralls
    - ./vendor/bin/phpunit Tests/
