<?php

namespace Mesd\FilterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilterRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterRowRepository extends EntityRepository
{
    public function getBySolvent($solvent)
    {
        $queryBuilder = $this->createQueryBuilder('filterRow');
        $queryBuilder->where(
            $queryBuilder->expr()->andX(
                $queryBuilder->expr()->eq('filterRow.solvent', ':solvent')
            )
        )->setParameter('solvent', $solvent);
        
        return $queryBuilder;
    }
}
