<?php

namespace Mesd\FilterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilterJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterJoinRepository extends EntityRepository
{
}
