<?php

namespace Mesd\FilterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilterAssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterAssociationRepository extends EntityRepository
{
    public function getCategoryAssociation($categoryEntityName, $associationName)
    {
        $queryBuilder = $this->createQueryBuilder('association');
        $queryBuilder->join(
            'association.categoryEntity',
            'categoryEntity',
            'WITH',
            $queryBuilder->expr()->andX(
                $queryBuilder->expr()->eq('categoryEntity.name', ':categoryEntityName'),
                $queryBuilder->expr()->eq('association.name', ':associationName')
            )
        )->setParameter('categoryEntityName', $categoryEntityName)
        ->setParameter('associationName', $associationName);
        
        return $queryBuilder;
    }
}
