<?php

namespace Mesd\FilterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilterCellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterCellRepository extends EntityRepository
{
    public function getBySolventAndAssociation($solvent, $associationId)
    {
        $queryBuilder = $this->createQueryBuilder('filterCell');
        $queryBuilder->join(
            'filterCell.filterAssociation',
            'filterAssociation',
            'WITH',
            $queryBuilder->expr()->andX(
                $queryBuilder->expr()->eq('filterAssociation.id', ':associationId'),
                $queryBuilder->expr()->eq('filterCell.solvent', ':solvent')
            )
        )->setParameter('associationId', $associationId)
        ->setParameter('solvent', ':solvent');
        
        return $queryBuilder;
    }
}
