<?php

namespace Mesd\FilterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilterAssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterAssociationRepository extends EntityRepository
{
    public function getCategoryAssociation($categoryName, $associationName)
    {
        $queryBuilder = $this->createQueryBuilder('association');
        $queryBuilder->join(
            'association.filterCategory',
            'category',
            'WITH',
            $queryBuilder->expr()->andX(
                $queryBuilder->expr()->eq('category.name', ':categoryName'),
                $queryBuilder->expr()->eq('association.name', ':associationName')
            )
        )->setParameter('categoryName', $categoryName)
        ->setParameter('associationName', $associationName);
        
        return $queryBuilder;
    }
}
