<?php

namespace Mesd\FilterBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * Generates the configuration tree.
     *
     * @return TreeBuilder
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('mesd_filter')
            ->addDefaultsIfNotSet()
            ->children()
                ->arrayNode('filter')
                    ->children()
                        ->arrayNode('bypass_roles')
                            ->prototype('scalar')
                            ->end()
                        ->end()
                        ->arrayNode('filters')
                            ->isRequired()
                            ->requiresAtLeastOneElement()
                            ->prototype('array')
                                ->children()
                                    ->arrayNode('entities')
                                        ->prototype('array')
                                            ->children()
                                                ->arrayNode('entity')
                                                    ->children()
                                                        ->scalarNode('name')
                                                        ->end()
                                                        ->arrayNode('joins')
                                                            ->prototype('array')
                                                                ->children()
                                                                    ->scalarNode('name')
                                                                    ->end()
                                                                    ->scalarNode('trail')
                                                                    ->end()
                                                                ->end()
                                                            ->end()
                                                        ->end()
                                                    ->end()
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('template')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('index')
                                    ->defaultValue('MesdFilterBundle:Filter:index.html.twig')
                                ->end()
                                ->scalarNode('edit')
                                    ->defaultValue('MesdFilterBundle:Filter:edit.html.twig')
                                ->end()
                                ->scalarNode('new')
                                    ->defaultValue('MesdFilterBundle:Filter:new.html.twig')
                                ->end()
                                ->scalarNode('show')
                                    ->defaultValue('MesdFilterBundle:Filter:show.html.twig')
                                ->end()
                                ->scalarNode('solvent')
                                    ->defaultValue('MesdFilterBundle:Filter:solvent.html.twig')
                                ->end()
                                ->scalarNode('eachuser')
                                    ->defaultValue('MesdFilterBundle:Filter:eachuser.html.twig')
                                ->end()
                                ->scalarNode('allusers')
                                    ->defaultValue('MesdFilterBundle:Filter:allusers.html.twig')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('login')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('revisit_behavior')
                            ->values(array('logout', 'redirect', 'status'))
                            ->defaultValue('status')
                        ->end()
                        ->scalarNode('revisit_redirect_target')
                            ->defaultValue(null)
                        ->end()
                        ->scalarNode('template')
                            ->defaultValue('MesdFilterBundle:Security:login.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('registration')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('approval_mail')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('approval_mail_from')
                            ->defaultValue('webmaster@example.com')
                        ->end()
                        ->scalarNode('approval_mail_subject')
                            ->defaultValue('Account Needs Approval')
                        ->end()
                        ->scalarNode('approval_mail_to')
                            ->defaultValue(null)
                        ->end()
                        ->booleanNode('approval_required')
                            ->defaultFalse()
                        ->end()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('link_text')
                            ->defaultValue('Create Account')
                        ->end()
                        ->booleanNode('mail_confirmation')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('mail_from')
                            ->defaultValue('webmaster@example.com')
                        ->end()
                        ->scalarNode('mail_subject')
                            ->defaultValue('Account Created')
                        ->end()
                        ->arrayNode('template')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('approve')
                                    ->defaultValue('MesdFilterBundle:Registration:approve.html.twig')
                                ->end()
                                ->scalarNode('approval_mail')
                                    ->defaultValue('MesdFilterBundle:Registration:approvalEmail.txt.twig')
                                ->end()
                                ->scalarNode('confirm')
                                    ->defaultValue('MesdFilterBundle:Registration:confirm.html.twig')
                                ->end()
                                ->scalarNode('confirm_mail')
                                    ->defaultValue('MesdFilterBundle:Registration:confirmEmail.txt.twig')
                                ->end()
                                ->scalarNode('register')
                                    ->defaultValue('MesdFilterBundle:Registration:register.html.twig')
                                ->end()
                                ->scalarNode('summary')
                                    ->defaultValue('MesdFilterBundle:Registration:summary.html.twig')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('reset')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('link_text')
                            ->defaultValue('Reset Password')
                        ->end()
                        ->scalarNode('mail_from')
                            ->defaultValue('webmaster@example.com')
                        ->end()
                        ->scalarNode('mail_subject')
                            ->defaultValue('Account Password Reset')
                        ->end()
                        ->arrayNode('template')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('already_requested')
                                    ->defaultValue('MesdFilterBundle:Reset:passwordAlreadyRequested.html.twig')
                                ->end()
                                ->scalarNode('check_email')
                                    ->defaultValue('MesdFilterBundle:Reset:checkEmail.html.twig')
                                ->end()
                                ->scalarNode('new_password')
                                    ->defaultValue('MesdFilterBundle:Reset:newPassword.html.twig')
                                ->end()
                                ->scalarNode('request')
                                    ->defaultValue('MesdFilterBundle:Reset:request.html.twig')
                                ->end()
                                ->scalarNode('reset_mail')
                                    ->defaultValue('MesdFilterBundle:Reset:resetEmail.txt.twig')
                                ->end()
                                ->scalarNode('success')
                                    ->defaultValue('MesdFilterBundle:Reset:success.html.twig')
                                ->end()
                            ->end()
                        ->end()
                        ->integerNode('token_ttl')
                            ->defaultValue(86400)
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
