filter:
    path:     /
    defaults: { _controller: "MesdFilterBundle:Filter:index" }

filter_show:
    path:     /{id}/show
    defaults: { _controller: "MesdFilterBundle:Filter:show" }

filter_new:
    path:     /new
    defaults: { _controller: "MesdFilterBundle:Filter:new" }

filter_create:
    path:     /create
    defaults: { _controller: "MesdFilterBundle:Filter:create" }
    methods:  POST

filter_edit:
    path:     /{id}/edit
    defaults: { _controller: "MesdFilterBundle:Filter:edit" }

filter_update:
    path:     /{id}/update
    defaults: { _controller: "MesdFilterBundle:Filter:update" }
    methods:  [POST, PUT]

filter_delete:
    path:     /{id}/delete
    defaults: { _controller: "MesdFilterBundle:Filter:delete" }
    methods:  [POST, DELETE]

MesdUserBundle_filter_category_data:
    path:     /category/{id}
    defaults: { _controller: "MesdFilterBundle:Filter:categoryData" }

MesdUserBundle_filter_create_cell:
    path:     /cell/create
    defaults: { _controller: "MesdFilterBundle:Filter:createCell" }
    methods:  POST

MesdUserBundle_filter_entity_data:
    path:     /entity/{id}
    defaults: { _controller: "MesdFilterBundle:Filter:entityData" }
